### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [ryanw-mobile/OctoMeter#292]
Hello, would you consider publishing the android app on F-Droid please?

**Comment by ryanw-mobile** [comment]
Thank you for your interest in our app.

At the moment, the app is not ready for publication on F-Droid. However, for evaluation purposes, the APK is available for download from our GitHub repository.

Please note that our license terms grant us exclusive rights to publish this app. Unauthorised publishing on any app store without our explicit permission is not permitted.
